Http request
saladuit/BuzingaServ pull request #19
Opened 2023-09-22 12:10 UTC by lucienvb

2023-09-22 13:33 UTC, saladuit requested changes
Looks good, only a few minor changes and all good!

2023-09-22 13:33 UTC, saladuit commented on src/HTTPRequest.cpp
> +HTTPRequest::HTTPRequest() {
Don't forget to initialise the private member variables with the initialiser list.

2023-09-22 13:33 UTC, saladuit commented on src/HTTPRequest.cpp
> +		_methodType = HTTPMethod::UNKNOWN;
I would substitue this with a logger message e.g.:
Logger &logger = Logger::getInstance();
...
logger.log(WARNING, "Unkown method");

2023-09-22 13:33 UTC, saladuit commented on src/main.cpp
> +	logger.log(LogLevel::INFO, "Body: %", test.getBody());
Perhaps nice to put all of the logging inside of the HTTP rquest class.

2023-09-29 09:40 UTC, lucienvb reviewed
Adjustments has been processed

2023-09-29 09:40 UTC, closed without merging