Configimplementation
saladuit/BuzingaServ pull request #42
Opened 2024-03-28 13:58 UTC by Tentanus

- Implemented configfile.

- [ ] The project still needs work on the listen directive. especially thinking about what ports are being used.

2024-03-28 15:48 UTC, saladuit requested changes

2024-03-28 16:12 UTC, saladuit commented on src/FileManager.cpp
> +// still need some elaboration for this part. it seems odd to append the buffer
moet eruit

2024-03-28 16:14 UTC, saladuit commented on src/HTTPServer.cpp
> +									 const ServerSettings &ServerSettings)
Dus niet hostname resolve, maar alle server settings, bij het aanmaken van der servers moeten dan op addrinus alle serversettings die dezelfde listen directive komen, als ie hem niet kan vinden zou ik gewoon een error throwen

2024-04-01 11:39 UTC, lucienvb commented on include/HTTPRequest.hpp
> +#ifndef HTTP_METHOD_ENUM
waarvoor dient dit?

2024-04-01 11:42 UTC, lucienvb commented on include/LocationSettings.hpp
>  	LocationSettings(const LocationSettings &rhs);
waar staat rhs voor?

2024-04-01 11:45 UTC, saladuit commented on include/LocationSettings.hpp
>  	LocationSettings(const LocationSettings &rhs);
Right hand side

2024-04-01 12:11 UTC, lucienvb approved these changes
Ziet er goed uit!

2024-04-08 09:02 UTC, saladuit approved these changes
Ik vind het lastig om hier nog eens door heen te gaan. In het vervolg protip. Als je zo'n grote pr maakt zorg dan dat je zoveel mogelijk extra info toevogd. Zoals 'hier ben ik niet zo zeker omdat, zus en zo' of 'dit zijn de belangrijke onderdelen waar ik nog deze vragen over heb'. Op die manier maak je het ook behapbaarder voor de gene die dingen nog na gaat. Ik ga hem voor nu gewoon approven en we zijn bij de eval wel wat er nog mis gaat

2024-04-28 18:35 UTC, Tentanus commented on include/Client.hpp
> +	ServerSettings _serversetting; // TODO: make multiple serverblocks work;
fixed

2024-05-06 09:59 UTC, saladuit approved these changes

2024-05-06 10:00 UTC, saladuit commented on src/Poll.cpp
> +		throw SystemException("poll"); // TODO: change poll_count 0 handler
It will display an error, but I wouldn't worry about it. It is protect so it will not crash

2024-05-06 10:02 UTC, saladuit commented on src/HTTPResponse.cpp
> +							  std::to_string(client_fd)); // TODO: handle error
je kan het testen door hier een system excpetion te throwen en te kijken wat er gebeurt. maar zoals ik het laatst had ingediend ja

2024-05-06 10:02 UTC, merged